// Deno KVの初期化と初期データ投入

import { getUserRepository } from "./users.ts";
import { getPostRepository } from "./posts.ts";
import { getWordRepository } from "./word.ts";

let kv: Deno.Kv | null = null;

// KVストアを取得（シングルトン）
export async function getKv(): Promise<Deno.Kv> {
  if (!kv) {
    kv = await Deno.openKv();
  }
  return kv;
}

// 初期データを投入
export async function initializeData() {
  const kv = await getKv();
  const userRepo = getUserRepository(kv);
  const postRepo = getPostRepository(kv);
  const wordRepo = getWordRepository(kv);

  // 既にデータが存在するかチェック
  const existingUsers = await userRepo.getAll();
  if (existingUsers.length > 0) {
    console.log("📦 初期データは既に投入済みです");
  } else {
    console.log("📦 初期データを投入中...");

    // Usersの初期データ
    await userRepo.create({ id: "1", name: "Taro" });
    await userRepo.create({ id: "2", name: "Hanako" });
    await userRepo.create({ id: "3", name: "SABURO" });
  }

  const existingPosts = await postRepo.getAll();
  if (existingPosts.length > 0) {
    console.log("📦 初期データは既に投入済みです");
  } else {
    // Postsの初期データ
    await postRepo.create({
      id: "1",
      title: "First Post",
      content: "This is the first post",
    });
    await postRepo.create({
      id: "2",
      title: "Second Post",
      content: "This is the second post",
    });
  }

  // LearningHistoryはユーザー単位で保持（リセットしない）

  // Wordsは毎回delete insertで最新化
  const existingWords = await wordRepo.getAll();
  if (existingWords.length > 0) {
    console.log("🗑️ 既存のWordsを削除中...");
    for (const word of existingWords) {
      await wordRepo.delete(word.id);
    }
  }

  // Wordsの初期データ（サンプル：単語・慣用句）
  const words = [
    // ビジネス (business) - 30件
    {
      id: "1",
      japanese: "締め切り",
      english: ["deadline"],
      difficulty: 1,
      frequency: 1,
      situation: "business",
    },
    {
      id: "2",
      japanese: "進捗",
      english: ["progress", "status"],
      difficulty: 2,
      frequency: 1,
      situation: "business",
    },
    {
      id: "3",
      japanese: "承認する",
      english: ["approve"],
      difficulty: 2,
      frequency: 1,
      situation: "business",
    },
    {
      id: "4",
      japanese: "会議",
      english: ["meeting", "conference"],
      difficulty: 1,
      frequency: 1,
      situation: "business",
    },
    {
      id: "5",
      japanese: "報告書",
      english: ["report"],
      difficulty: 2,
      frequency: 1,
      situation: "business",
    },
    {
      id: "6",
      japanese: "見積もり",
      english: ["estimate", "quotation"],
      difficulty: 2,
      frequency: 1,
      situation: "business",
    },
    {
      id: "7",
      japanese: "契約",
      english: ["contract", "agreement"],
      difficulty: 2,
      frequency: 1,
      situation: "business",
    },
    {
      id: "8",
      japanese: "交渉",
      english: ["negotiation"],
      difficulty: 3,
      frequency: 1,
      situation: "business",
    },
    {
      id: "9",
      japanese: "提案",
      english: ["proposal", "suggestion"],
      difficulty: 2,
      frequency: 1,
      situation: "business",
    },
    {
      id: "10",
      japanese: "予算",
      english: ["budget"],
      difficulty: 2,
      frequency: 1,
      situation: "business",
    },
    {
      id: "11",
      japanese: "売上",
      english: ["sales", "revenue"],
      difficulty: 2,
      frequency: 1,
      situation: "business",
    },
    {
      id: "12",
      japanese: "利益",
      english: ["profit"],
      difficulty: 2,
      frequency: 1,
      situation: "business",
    },
    {
      id: "13",
      japanese: "損失",
      english: ["loss"],
      difficulty: 2,
      frequency: 1,
      situation: "business",
    },
    {
      id: "14",
      japanese: "顧客",
      english: ["customer", "client"],
      difficulty: 1,
      frequency: 1,
      situation: "business",
    },
    {
      id: "15",
      japanese: "取引先",
      english: ["business partner", "supplier"],
      difficulty: 2,
      frequency: 1,
      situation: "business",
    },
    {
      id: "16",
      japanese: "納期",
      english: ["delivery date", "due date"],
      difficulty: 2,
      frequency: 1,
      situation: "business",
    },
    {
      id: "17",
      japanese: "在庫",
      english: ["inventory", "stock"],
      difficulty: 2,
      frequency: 1,
      situation: "business",
    },
    {
      id: "18",
      japanese: "発注",
      english: ["order", "purchase order"],
      difficulty: 2,
      frequency: 1,
      situation: "business",
    },
    {
      id: "19",
      japanese: "請求書",
      english: ["invoice", "bill"],
      difficulty: 2,
      frequency: 1,
      situation: "business",
    },
    {
      id: "20",
      japanese: "領収書",
      english: ["receipt"],
      difficulty: 1,
      frequency: 1,
      situation: "business",
    },
    {
      id: "21",
      japanese: "資料",
      english: ["materials", "documents"],
      difficulty: 1,
      frequency: 1,
      situation: "business",
    },
    {
      id: "22",
      japanese: "議事録",
      english: ["minutes", "meeting notes"],
      difficulty: 3,
      frequency: 1,
      situation: "business",
    },
    {
      id: "23",
      japanese: "担当者",
      english: ["person in charge", "representative"],
      difficulty: 2,
      frequency: 1,
      situation: "business",
    },
    {
      id: "24",
      japanese: "部署",
      english: ["department", "division"],
      difficulty: 2,
      frequency: 1,
      situation: "business",
    },
    {
      id: "25",
      japanese: "研修",
      english: ["training"],
      difficulty: 2,
      frequency: 1,
      situation: "business",
    },
    {
      id: "26",
      japanese: "出張",
      english: ["business trip"],
      difficulty: 2,
      frequency: 1,
      situation: "business",
    },
    {
      id: "27",
      japanese: "残業",
      english: ["overtime"],
      difficulty: 2,
      frequency: 1,
      situation: "business",
    },
    {
      id: "28",
      japanese: "有給休暇",
      english: ["paid leave", "paid vacation"],
      difficulty: 2,
      frequency: 1,
      situation: "business",
    },
    {
      id: "29",
      japanese: "経費",
      english: ["expenses"],
      difficulty: 2,
      frequency: 1,
      situation: "business",
    },
    {
      id: "30",
      japanese: "決算",
      english: ["settlement", "closing accounts"],
      difficulty: 3,
      frequency: 1,
      situation: "business",
    },

    // 旅行 (travel) - 30件
    {
      id: "31",
      japanese: "片道",
      english: ["one way", "one-way"],
      difficulty: 1,
      frequency: 1,
      situation: "travel",
    },
    {
      id: "32",
      japanese: "往復",
      english: ["round trip", "round-trip"],
      difficulty: 1,
      frequency: 1,
      situation: "travel",
    },
    {
      id: "33",
      japanese: "乗り換え",
      english: ["transfer", "connection"],
      difficulty: 2,
      frequency: 1,
      situation: "travel",
    },
    {
      id: "34",
      japanese: "搭乗券",
      english: ["boarding pass"],
      difficulty: 2,
      frequency: 1,
      situation: "travel",
    },
    {
      id: "35",
      japanese: "手荷物",
      english: ["carry-on", "hand luggage"],
      difficulty: 2,
      frequency: 1,
      situation: "travel",
    },
    {
      id: "36",
      japanese: "預け荷物",
      english: ["checked baggage"],
      difficulty: 2,
      frequency: 1,
      situation: "travel",
    },
    {
      id: "37",
      japanese: "税関",
      english: ["customs"],
      difficulty: 2,
      frequency: 1,
      situation: "travel",
    },
    {
      id: "38",
      japanese: "入国審査",
      english: ["immigration"],
      difficulty: 2,
      frequency: 1,
      situation: "travel",
    },
    {
      id: "39",
      japanese: "出発",
      english: ["departure"],
      difficulty: 1,
      frequency: 1,
      situation: "travel",
    },
    {
      id: "40",
      japanese: "到着",
      english: ["arrival"],
      difficulty: 1,
      frequency: 1,
      situation: "travel",
    },
    {
      id: "41",
      japanese: "遅延",
      english: ["delay"],
      difficulty: 2,
      frequency: 1,
      situation: "travel",
    },
    {
      id: "42",
      japanese: "欠航",
      english: ["cancellation", "cancelled flight"],
      difficulty: 2,
      frequency: 1,
      situation: "travel",
    },
    {
      id: "43",
      japanese: "乗り遅れる",
      english: ["miss"],
      difficulty: 2,
      frequency: 1,
      situation: "travel",
    },
    {
      id: "44",
      japanese: "パスポート",
      english: ["passport"],
      difficulty: 1,
      frequency: 1,
      situation: "travel",
    },
    {
      id: "45",
      japanese: "ビザ",
      english: ["visa"],
      difficulty: 1,
      frequency: 1,
      situation: "travel",
    },
    {
      id: "46",
      japanese: "両替",
      english: ["currency exchange"],
      difficulty: 2,
      frequency: 1,
      situation: "travel",
    },
    {
      id: "47",
      japanese: "観光",
      english: ["sightseeing", "tourism"],
      difficulty: 1,
      frequency: 1,
      situation: "travel",
    },
    {
      id: "48",
      japanese: "名所",
      english: ["tourist spot", "attraction"],
      difficulty: 2,
      frequency: 1,
      situation: "travel",
    },
    {
      id: "49",
      japanese: "宿泊",
      english: ["accommodation", "stay"],
      difficulty: 2,
      frequency: 1,
      situation: "travel",
    },
    {
      id: "50",
      japanese: "チェックイン",
      english: ["check-in"],
      difficulty: 1,
      frequency: 1,
      situation: "travel",
    },
    {
      id: "51",
      japanese: "チェックアウト",
      english: ["check-out"],
      difficulty: 1,
      frequency: 1,
      situation: "travel",
    },
    {
      id: "52",
      japanese: "空室",
      english: ["vacancy", "available room"],
      difficulty: 2,
      frequency: 1,
      situation: "travel",
    },
    {
      id: "53",
      japanese: "満室",
      english: ["no vacancy", "fully booked"],
      difficulty: 2,
      frequency: 1,
      situation: "travel",
    },
    {
      id: "54",
      japanese: "案内所",
      english: ["information center"],
      difficulty: 2,
      frequency: 1,
      situation: "travel",
    },
    {
      id: "55",
      japanese: "地図",
      english: ["map"],
      difficulty: 1,
      frequency: 1,
      situation: "travel",
    },
    {
      id: "56",
      japanese: "道に迷う",
      english: ["get lost"],
      difficulty: 2,
      frequency: 1,
      situation: "travel",
    },
    {
      id: "57",
      japanese: "時差ぼけ",
      english: ["jet lag"],
      difficulty: 2,
      frequency: 1,
      situation: "travel",
    },
    {
      id: "58",
      japanese: "土産",
      english: ["souvenir"],
      difficulty: 2,
      frequency: 1,
      situation: "travel",
    },
    {
      id: "59",
      japanese: "免税店",
      english: ["duty-free shop"],
      difficulty: 2,
      frequency: 1,
      situation: "travel",
    },
    {
      id: "60",
      japanese: "荷造り",
      english: ["packing"],
      difficulty: 2,
      frequency: 1,
      situation: "travel",
    },

    // 日常 (daily) - 30件
    {
      id: "61",
      japanese: "一石二鳥",
      english: ["kill two birds with one stone"],
      difficulty: 2,
      frequency: 2,
      situation: "daily",
    },
    {
      id: "62",
      japanese: "時は金なり",
      english: ["time is money"],
      difficulty: 2,
      frequency: 2,
      situation: "daily",
    },
    {
      id: "63",
      japanese: "早起きは三文の徳",
      english: ["the early bird catches the worm"],
      difficulty: 3,
      frequency: 2,
      situation: "daily",
    },
    {
      id: "64",
      japanese: "習うより慣れよ",
      english: ["practice makes perfect"],
      difficulty: 2,
      frequency: 2,
      situation: "daily",
    },
    {
      id: "65",
      japanese: "郷に入れば郷に従え",
      english: ["when in Rome, do as the Romans do"],
      difficulty: 3,
      frequency: 2,
      situation: "daily",
    },
    {
      id: "66",
      japanese: "天気",
      english: ["weather"],
      difficulty: 1,
      frequency: 1,
      situation: "daily",
    },
    {
      id: "67",
      japanese: "晴れ",
      english: ["sunny", "clear"],
      difficulty: 1,
      frequency: 1,
      situation: "daily",
    },
    {
      id: "68",
      japanese: "曇り",
      english: ["cloudy"],
      difficulty: 1,
      frequency: 1,
      situation: "daily",
    },
    {
      id: "69",
      japanese: "雨",
      english: ["rain", "rainy"],
      difficulty: 1,
      frequency: 1,
      situation: "daily",
    },
    {
      id: "70",
      japanese: "傘",
      english: ["umbrella"],
      difficulty: 1,
      frequency: 1,
      situation: "daily",
    },
    {
      id: "71",
      japanese: "朝食",
      english: ["breakfast"],
      difficulty: 1,
      frequency: 1,
      situation: "daily",
    },
    {
      id: "72",
      japanese: "昼食",
      english: ["lunch"],
      difficulty: 1,
      frequency: 1,
      situation: "daily",
    },
    {
      id: "73",
      japanese: "夕食",
      english: ["dinner", "supper"],
      difficulty: 1,
      frequency: 1,
      situation: "daily",
    },
    {
      id: "74",
      japanese: "おやつ",
      english: ["snack"],
      difficulty: 1,
      frequency: 1,
      situation: "daily",
    },
    {
      id: "75",
      japanese: "趣味",
      english: ["hobby"],
      difficulty: 1,
      frequency: 1,
      situation: "daily",
    },
    {
      id: "76",
      japanese: "散歩",
      english: ["walk", "stroll"],
      difficulty: 1,
      frequency: 1,
      situation: "daily",
    },
    {
      id: "77",
      japanese: "運動",
      english: ["exercise"],
      difficulty: 1,
      frequency: 1,
      situation: "daily",
    },
    {
      id: "78",
      japanese: "掃除",
      english: ["cleaning"],
      difficulty: 1,
      frequency: 1,
      situation: "daily",
    },
    {
      id: "79",
      japanese: "洗濯",
      english: ["laundry"],
      difficulty: 1,
      frequency: 1,
      situation: "daily",
    },
    {
      id: "80",
      japanese: "料理",
      english: ["cooking"],
      difficulty: 1,
      frequency: 1,
      situation: "daily",
    },
    {
      id: "81",
      japanese: "買い物",
      english: ["shopping"],
      difficulty: 1,
      frequency: 1,
      situation: "daily",
    },
    {
      id: "82",
      japanese: "約束",
      english: ["appointment", "promise"],
      difficulty: 1,
      frequency: 1,
      situation: "daily",
    },
    {
      id: "83",
      japanese: "待ち合わせ",
      english: ["meeting up", "rendezvous"],
      difficulty: 2,
      frequency: 1,
      situation: "daily",
    },
    {
      id: "84",
      japanese: "遅刻",
      english: ["late", "being late"],
      difficulty: 1,
      frequency: 1,
      situation: "daily",
    },
    {
      id: "85",
      japanese: "体調",
      english: ["physical condition"],
      difficulty: 2,
      frequency: 1,
      situation: "daily",
    },
    {
      id: "86",
      japanese: "風邪",
      english: ["cold"],
      difficulty: 1,
      frequency: 1,
      situation: "daily",
    },
    {
      id: "87",
      japanese: "薬",
      english: ["medicine"],
      difficulty: 1,
      frequency: 1,
      situation: "daily",
    },
    {
      id: "88",
      japanese: "病院",
      english: ["hospital"],
      difficulty: 1,
      frequency: 1,
      situation: "daily",
    },
    {
      id: "89",
      japanese: "睡眠",
      english: ["sleep"],
      difficulty: 1,
      frequency: 1,
      situation: "daily",
    },
    {
      id: "90",
      japanese: "疲れ",
      english: ["tiredness", "fatigue"],
      difficulty: 1,
      frequency: 1,
      situation: "daily",
    },

    // ショッピング (shopping) - 30件
    {
      id: "91",
      japanese: "割引",
      english: ["discount"],
      difficulty: 1,
      frequency: 1,
      situation: "shopping",
    },
    {
      id: "92",
      japanese: "在庫切れ",
      english: ["out of stock", "sold out"],
      difficulty: 2,
      frequency: 1,
      situation: "shopping",
    },
    {
      id: "93",
      japanese: "予約",
      english: ["reservation", "booking"],
      difficulty: 1,
      frequency: 1,
      situation: "shopping",
    },
    {
      id: "94",
      japanese: "キャンセル",
      english: ["cancel", "cancellation"],
      difficulty: 1,
      frequency: 1,
      situation: "shopping",
    },
    {
      id: "95",
      japanese: "返品",
      english: ["return"],
      difficulty: 2,
      frequency: 1,
      situation: "shopping",
    },
    {
      id: "96",
      japanese: "交換",
      english: ["exchange"],
      difficulty: 2,
      frequency: 1,
      situation: "shopping",
    },
    {
      id: "97",
      japanese: "試着",
      english: ["fitting", "try on"],
      difficulty: 2,
      frequency: 1,
      situation: "shopping",
    },
    {
      id: "98",
      japanese: "サイズ",
      english: ["size"],
      difficulty: 1,
      frequency: 1,
      situation: "shopping",
    },
    {
      id: "99",
      japanese: "色",
      english: ["color"],
      difficulty: 1,
      frequency: 1,
      situation: "shopping",
    },
    {
      id: "100",
      japanese: "現金",
      english: ["cash"],
      difficulty: 1,
      frequency: 1,
      situation: "shopping",
    },
    {
      id: "101",
      japanese: "クレジットカード",
      english: ["credit card"],
      difficulty: 1,
      frequency: 1,
      situation: "shopping",
    },
    {
      id: "102",
      japanese: "レシート",
      english: ["receipt"],
      difficulty: 1,
      frequency: 1,
      situation: "shopping",
    },
    {
      id: "103",
      japanese: "袋",
      english: ["bag"],
      difficulty: 1,
      frequency: 1,
      situation: "shopping",
    },
    {
      id: "104",
      japanese: "包装",
      english: ["wrapping", "gift wrap"],
      difficulty: 2,
      frequency: 1,
      situation: "shopping",
    },
    {
      id: "105",
      japanese: "配送",
      english: ["delivery", "shipping"],
      difficulty: 2,
      frequency: 1,
      situation: "shopping",
    },
    {
      id: "106",
      japanese: "送料",
      english: ["shipping fee"],
      difficulty: 2,
      frequency: 1,
      situation: "shopping",
    },
    {
      id: "107",
      japanese: "保証",
      english: ["warranty", "guarantee"],
      difficulty: 2,
      frequency: 1,
      situation: "shopping",
    },
    {
      id: "108",
      japanese: "新品",
      english: ["brand new"],
      difficulty: 1,
      frequency: 1,
      situation: "shopping",
    },
    {
      id: "109",
      japanese: "中古",
      english: ["used", "second-hand"],
      difficulty: 2,
      frequency: 1,
      situation: "shopping",
    },
    {
      id: "110",
      japanese: "セール",
      english: ["sale"],
      difficulty: 1,
      frequency: 1,
      situation: "shopping",
    },
    {
      id: "111",
      japanese: "定価",
      english: ["regular price", "list price"],
      difficulty: 2,
      frequency: 1,
      situation: "shopping",
    },
    {
      id: "112",
      japanese: "税込み",
      english: ["tax included"],
      difficulty: 2,
      frequency: 1,
      situation: "shopping",
    },
    {
      id: "113",
      japanese: "税抜き",
      english: ["before tax", "tax excluded"],
      difficulty: 2,
      frequency: 1,
      situation: "shopping",
    },
    {
      id: "114",
      japanese: "お釣り",
      english: ["change"],
      difficulty: 1,
      frequency: 1,
      situation: "shopping",
    },
    {
      id: "115",
      japanese: "会計",
      english: ["checkout", "payment"],
      difficulty: 2,
      frequency: 1,
      situation: "shopping",
    },
    {
      id: "116",
      japanese: "レジ",
      english: ["cash register", "checkout counter"],
      difficulty: 1,
      frequency: 1,
      situation: "shopping",
    },
    {
      id: "117",
      japanese: "店員",
      english: ["store clerk", "sales associate"],
      difficulty: 1,
      frequency: 1,
      situation: "shopping",
    },
    {
      id: "118",
      japanese: "営業時間",
      english: ["business hours"],
      difficulty: 2,
      frequency: 1,
      situation: "shopping",
    },
    {
      id: "119",
      japanese: "定休日",
      english: ["regular holiday", "closed day"],
      difficulty: 2,
      frequency: 1,
      situation: "shopping",
    },
    {
      id: "120",
      japanese: "品質",
      english: ["quality"],
      difficulty: 2,
      frequency: 1,
      situation: "shopping",
    },
  ];

  for (const word of words) {
    await wordRepo.create(word);
  }

  console.log(`✅ Wordsの投入が完了しました（${words.length}件）`);
}
